server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_boot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_spring_boot
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 701863208512-vi4b84dcuj8rvkl1m459osjfn69en2dv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1209189736310043
            client-secret: 5fa78598ee7b915763d5eff788887551
            scope:
              - email
              - public_profile

          naver:
            client-id: 0mY7DbcGGuV55TNKEobw
            client-secret: v33kaZlxt3
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/naver

          kakao:
            client-id: 3ce802972bb901eae2c5bb09a589311e
            client-secret: vTHjVVcxbL8Kc4JctXoTqiT7SETOBckF
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: POST
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/kakao

          github:
            client-id: 326197fcea08b8285c0e
            client-secret: 6afa937c07d18f931d759366dda35c7b5ae7138f
            redirect-uri: http://localhost:9090/login/oauth2/code/github

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # 회원정보를 json 으로 받는데 'response' 라는 키값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # 회원정보를 json 으로 받는데 'properties' 라는 키값으로 네이버가 리턴해줌



  # 타임리프 캐시 무효화
  thymeleaf:
    cache: false

  mail:
    host: smtp.naver.com
    port: 465
    username: oloveo24@naver.com
    password: tlsqlgkstjwo5
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
